# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - clmsAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://acrclms.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_917f4572ca424c87a3ad021189fa5702 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f7d43190f76d4339b3283849341e3d43 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: acrclms.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_917f4572ca424c87a3ad021189fa5702 }}/test:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'clmsAPI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_33d2849bed4e48beb6a290fe1f603163 }}
        images: 'acrclms.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_917f4572ca424c87a3ad021189fa5702 }}/test:${{ github.sha }}'